[tool.black]
line-length = 120
target-version = ["py39"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 120
known_third_party = ["torch", "numpy", "ale_py"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[tool.ruff]
line-length = 120
target-version = "py39"
fix = true

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "C90"]
ignore = [
  "E501",  # line too long (handled by black)
  "F403",  # 'from module import *' used
  "F401",  # unused imports (during dev)
]
exclude = ["tests/", "build/", ".venv/"]

[tool.ruff.lint.mccabe]
max-complexity = 60

[tool.ruff.format]
indent-style = "space"
quote-style = "preserve"
line-ending = "lf"

[tool.pyright]
pythonVersion = "3.9"
typeCheckingMode = "basic"
